"""Add oab_number, oab_state, cpf, address, phone to users table

Revision ID: 4a84801a8617
Revises: 1cd60594c6cd
Create Date: 2025-09-01 13:38:35.669362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a84801a8617'
down_revision: Union[str, Sequence[str], None] = '1cd60594c6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('rg', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('profession', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('clients', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('clients', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_index(op.f('ix_clients_cpf'), 'clients', ['cpf'], unique=True)
    op.create_index(op.f('ix_clients_full_name'), 'clients', ['full_name'], unique=False)
    op.drop_column('clients', 'name')
    op.alter_column('extrajudicial_cases', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('processes', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('task_columns', 'owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('users', sa.Column('oab_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oab_state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'oab_state')
    op.drop_column('users', 'oab_number')
    op.alter_column('task_columns', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('processes', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('extrajudicial_cases', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('clients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_full_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_cpf'), table_name='clients')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.alter_column('clients', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('clients', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'profession')
    op.drop_column('clients', 'marital_status')
    op.drop_column('clients', 'nationality')
    op.drop_column('clients', 'rg')
    op.drop_column('clients', 'cpf')
    op.drop_column('clients', 'full_name')
    # ### end Alembic commands ###
