"""Cria a tabela de intimações

Revision ID: 686e38194ff1
Revises: 934dc7f919ec
Create Date: 2025-10-01 18:28:38.284520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686e38194ff1'
down_revision: Union[str, Sequence[str], None] = '934dc7f919ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intimations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('process_number', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intimations_process_number'), 'intimations', ['process_number'], unique=False)
    op.create_index(op.f('ix_intimations_publication_date'), 'intimations', ['publication_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intimations_publication_date'), table_name='intimations')
    op.drop_index(op.f('ix_intimations_process_number'), table_name='intimations')
    op.drop_table('intimations')
    # ### end Alembic commands ###
