"""Add fields and align models with db

Revision ID: b7d0317fd72d
Revises: 1cd60594c6cd
Create Date: 2025-09-01 15:42:30.013801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d0317fd72d'
down_revision: Union[str, Sequence[str], None] = '1cd60594c6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('rg', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('profession', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('clients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.create_index(op.f('ix_clients_cpf'), 'clients', ['cpf'], unique=True)
    op.create_index(op.f('ix_clients_full_name'), 'clients', ['full_name'], unique=False)
    op.drop_column('clients', 'name')
    op.add_column('users', sa.Column('oab_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('oab_state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cpf', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'address')
    op.drop_column('users', 'cpf')
    op.drop_column('users', 'oab_state')
    op.drop_column('users', 'oab_number')
    op.add_column('clients', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_full_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_cpf'), table_name='clients')
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'address')
    op.drop_column('clients', 'profession')
    op.drop_column('clients', 'marital_status')
    op.drop_column('clients', 'nationality')
    op.drop_column('clients', 'rg')
    op.drop_column('clients', 'cpf')
    op.drop_column('clients', 'full_name')
    # ### end Alembic commands ###
